name: v1 CI

on:
  push:
    branches: [ "legacy" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run legacy tests
        run: echo "Running old tests..."
